# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='lip',
            field=models.CharField(default='abc', max_length=32),
            preserve_default=False,
        ),
    ]
